### ISSUE TITLE
Some parts of documentation outdated?

### ISSUE THREAD

**Issue by trahflow** [Seelengrab/FieldFlags.jl#14]
The documentation mentions a zero-arg constructor for @bitflags types.
But both, the example in the documentation and a local test (on version 0.4.0) show that such a constructor doesn't exist.
Maybe just a matter of updating the docs?

**Comment by trahflow** [comment]
Documentation also says

> [...] While currently field sizes larger than 1 return an UInt, this is in particular not guaranteed and may be changed in the future, so that e.g. a field of size 2 returns an UInt8 instead.

This also seems to have changed already?

Btw. Really nice package! :)

**Comment by Seelengrab** [comment]
Oof, yes 🤦 Seems like I missed parts of the docs with the last release https://github.com/Seelengrab/FieldFlags.jl/releases/tag/v0.4.0

I'll fix the docs shortly!

**Comment by Seelengrab** [comment]
Alright, docs are fixed! Thanks for reporting this :)

**Comment by trahflow** [comment]
thanks for the super quick reaction!
